"""
Unit tests for app/settings.py.

Focuses on the production-hardening changes:
- firecrawl_mcp_url excluded from model serialisation
- admin API key not logged in plaintext
- mcp_connections structure
"""

import logging
import re

import pytest


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _make_settings(**kwargs):
    """Construct a Settings instance with test values, overriding env vars."""
    from app.settings import Settings
    defaults = dict(
        firecrawl_api_key="test-fc-secret",
        google_api_key="test-goog-key",
        admin_api_key="test-admin-key",
    )
    defaults.update(kwargs)
    return Settings(**defaults)


# ---------------------------------------------------------------------------
# Firecrawl key serialisation
# ---------------------------------------------------------------------------

class TestFirecrawlKeySerialisation:
    def test_firecrawl_url_absent_from_model_dump(self):
        """firecrawl_mcp_url must not appear as a key in model_dump()."""
        s = _make_settings(firecrawl_api_key="super-secret-fc")
        dumped = s.model_dump()
        assert "firecrawl_mcp_url" not in dumped

    def test_firecrawl_key_absent_from_model_dump_values(self):
        """The raw API key string must not appear anywhere in model_dump() output."""
        s = _make_settings(firecrawl_api_key="unique-sentinel-key")
        assert "unique-sentinel-key" not in str(s.model_dump())

    def test_firecrawl_key_absent_from_repr(self):
        """repr(settings) must not expose the raw Firecrawl API key."""
        s = _make_settings(firecrawl_api_key="repr-sentinel-key")
        assert "repr-sentinel-key" not in repr(s)

    def test_firecrawl_url_property_embeds_key(self):
        """firecrawl_mcp_url property must embed the key in the URL path."""
        s = _make_settings(firecrawl_api_key="my-actual-fc-key")
        url = s.firecrawl_mcp_url
        assert "my-actual-fc-key" in url
        assert url.startswith("https://mcp.firecrawl.dev/")
        assert url.endswith("/v2/mcp")

    def test_firecrawl_url_is_plain_property_not_computed_field(self):
        """firecrawl_mcp_url must be a plain @property, not a pydantic computed_field."""
        from app.settings import Settings
        # computed_fields are registered in model_computed_fields
        assert "firecrawl_mcp_url" not in Settings.model_computed_fields


# ---------------------------------------------------------------------------
# Admin key logging
# ---------------------------------------------------------------------------

class TestAdminKeyLogging:
    def test_autogenerated_key_not_in_log(self, caplog):
        """When admin_api_key is empty the log warning must not contain the key value."""
        with caplog.at_level(logging.WARNING, logger="app.settings"):
            s = _make_settings(admin_api_key="")  # empty → triggers auto-generation

        # A key was generated (non-empty)
        assert s.admin_api_key, "Expected admin_api_key to be auto-generated"

        # Find the ephemeral-key warning
        warnings = [r.message for r in caplog.records if "ephemeral" in r.message.lower()]
        assert warnings, "Expected at least one 'ephemeral key' warning log entry"

        for msg in warnings:
            # A URL-safe token of 32 bytes encodes to ~43 base64url chars.
            # The message must not contain any such long token.
            assert not re.search(r"[A-Za-z0-9_\-]{32,}", msg), (
                f"Log warning appears to contain the key value: {msg!r}"
            )

    def test_explicit_admin_key_not_logged(self, caplog):
        """When ADMIN_API_KEY is set no ephemeral-key warning should appear."""
        with caplog.at_level(logging.WARNING, logger="app.settings"):
            _make_settings(admin_api_key="explicit-key")

        ephemeral_warnings = [
            r for r in caplog.records if "ephemeral" in r.message.lower()
        ]
        assert not ephemeral_warnings


# ---------------------------------------------------------------------------
# MCP connections structure
# ---------------------------------------------------------------------------

class TestMcpConnections:
    def test_mcp_connections_has_expected_servers(self):
        """mcp_connections must include both firecrawl and langchain_docs."""
        s = _make_settings()
        conns = s.mcp_connections
        assert "firecrawl" in conns
        assert "langchain_docs" in conns

    def test_firecrawl_uses_streamable_http(self):
        s = _make_settings()
        assert s.mcp_connections["firecrawl"]["transport"] == "streamable_http"

    def test_langchain_docs_uses_streamable_http(self):
        s = _make_settings()
        assert s.mcp_connections["langchain_docs"]["transport"] == "streamable_http"

    def test_firecrawl_url_in_connections(self):
        """mcp_connections firecrawl URL must embed the API key."""
        s = _make_settings(firecrawl_api_key="conn-test-key")
        assert "conn-test-key" in s.mcp_connections["firecrawl"]["url"]

    def test_langchain_docs_url_configurable(self):
        """langchain_docs URL can be overridden via langchain_docs_mcp_url."""
        s = _make_settings(langchain_docs_mcp_url="https://custom.example.com/mcp")
        assert s.mcp_connections["langchain_docs"]["url"] == "https://custom.example.com/mcp"
